services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: "on-failure"

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: "on-failure"

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: "on-failure"

networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      device: ${USER_HOME}/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      device: ${USER_HOME}/data/wordpress
      o: bind
