FROM wordpress

# EXPOSE 9000

# # Install wp cli
# RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

# # Copy the configuration files
# COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf
# # COPY ./tools/config.sh /home
# # RUN chmod 777 /home/config.sh
